services:
  ds:
    build:
      context: .
      dockerfile: Dockerfile
    image: ds:latest
    restart: on-failure
    volumes:
      - ./:/app
    env_file:
      - config.env
    network_mode: bridge
