[tool.ruff]
# https://docs.astral.sh/ruff
show-fixes = true
line-length = 120
indent-width = 4
target-version = "py312"
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
[tool.ruff.lint]
preview = true
select = [
    "W", # warning
    "F", # pyflakes
    "I", # isort
    "A", # flake8-builtins
    "SIM", # flake8-simplify
    "C4", # flake8-comprehensions
    "B", # flake8-bugbear
    "PIE", # flake8-pie
    "RET", # flake8-return
    "TID", # flake8-tidy-imports
    "CPY", # flake8-copyright
    "UP", # pyupgrade
    "FURB", # refurb
    "PERF", # perflint
    "RUF", # ruff-specific rules
    "PLR6201", # Pylint: literal-membership
    "PLC1901", # Pylint: compare-to-empty-string
]
# https://docs.astral.sh/ruff/rules/
ignore=[
  "I001",
  "B904",
  "RET502",
  "RET503",
  "RUF001",
  "RUF017",
  "FURB118",
  "RUF052",
]
[tool.ruff.lint.isort]
force-single-line = true
combine-as-imports = true
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
known-first-party = ["ds"]

[tool.isort]
# https://github.com/PyCQA/isort
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 4
use_parentheses = true
ensure_newline_before_comments = true
lines_between_sections = 0
no_inline_sort = true
combine_as_imports = true
default_section = "THIRDPARTY"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = "ds"
