# Copyright (C) 2023-present kastaid
# https://github.com/kastaid/ds
# MIT License

import asyncio
import subprocess
import sys

try:
    import pyrogram as pyro
except ModuleNotFoundError:
    print("Installing Pyrogram...")
    subprocess.check_call(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            "--upgrade",
            "pyrofork==2.3.69",
        ]
    )
finally:
    import pyrogram as pyro

usage = """
Go to "my.telegram.org" (to get API_ID and API_HASH):
• Login with your Telegram account.
• Click on API development tools.
• Create a new application with the required details.

API_ID is "App api_id:"
API_HASH is "App api_hash:"
"""

template = """
<b>{} Userbot Client</b> <code>STRING_SESSION</code>
⚠️ <b>DO NOT SHARE TO ANYONE</b> ⚠️

<pre>{}</pre>

Generated by DS ( strgen.py – @kastaid )
"""

generated = """
Check your Telegram "Saved Messages" to copy STRING_SESSION or copy from above.
"""

print(usage)

try:
    API_ID = int(input("Enter your API_ID here: "))
except ValueError:
    print(">> API_ID must be an integer.\nQuitting...")
    sys.exit(0)
API_HASH = input("Enter your API_HASH here: ")
if not API_HASH:
    print(">> API_HASH must not be empty!\nQuitting...")
    sys.exit(0)

client = pyro.Client(
    "ds",
    api_id=API_ID,
    api_hash=API_HASH,
    in_memory=True,
)


async def main() -> None:
    async with client:
        try:
            await asyncio.sleep(1)
            print("Generating Pyrogram STRING_SESSION...")
            string_session = await client.export_session_string()
            saved_messages = template.format("Pyrogram", string_session)
            print("\n" + string_session + "\n")
            await client.send_message(
                "me",
                saved_messages,
                parse_mode=pyro.enums.ParseMode.HTML,
            )
            await asyncio.sleep(1)
            print(generated)
        except pyro.errors.ApiIdInvalid:
            print(">> Your API_ID or API_HASH combination is invalid. Kindly recheck.\nQuitting...")
            sys.exit(1)
        except pyro.errors.PhoneNumberInvalid:
            print(">> The phone number is invalid!\nQuitting...")
            sys.exit(1)


asyncio.run(main())
