# Copyright (C) 2023-present kastaid
# https://github.com/kastaid/ds
# MIT License

import asyncio
import random
import subprocess
import sys

PACKAGE = "pyrofork==2.3.69"
DELAY_RANGE = (1.5, 2.5)
SHORT_DELAY = 1.5

usage = """Go to "my.telegram.org" (to get API_ID and API_HASH):
• Login with your Telegram account.
• Click "API development tools".
• Create a new application with the required details.

API_ID is "App api_id:"
API_HASH is "App api_hash:"
"""
generating = "Generating STRING_SESSION for {} v{}..."
saved_message = """<b>{library} Userbot Client</b> <code>STRING_SESSION</code>
⚠️ <b>DO NOT SHARE TO ANYONE</b> ⚠️

<b>USER_ID</b>:
<code>{user_id}</code>
<b>API_ID</b>:
<code>{api_id}</code>
<b>API_HASH</b>:
<code>{api_hash}</code>
<b>PHONE_NUMBER</b>:
<code>{phone_number}</code>
<b>STRING_SESSION</b>:
<pre>{string_session}</pre>

Generated by KASTA (https://t.me/kastaid)"""
generated = """
Check your Telegram "Saved Messages" to copy STRING_SESSION,
or copy it from above.

Generated by KASTA (https://t.me/kastaid)
"""


def ensure_package():
    try:
        __import__("pyrogram")
    except ModuleNotFoundError:
        print(f"Installing {PACKAGE}...")
        args = [
            "pip",
            "install",
            "--break-system-packages",
            PACKAGE,
        ]
        try:
            subprocess.check_call(
                ["uv", *args],
                stdout=subprocess.DEVNULL,
            )
        except (
            FileNotFoundError,
            subprocess.CalledProcessError,
        ):
            subprocess.check_call(
                [sys.executable, "-m", *args],
                stdout=subprocess.DEVNULL,
            )
        print(f"{PACKAGE} installed successfully.")


def get_api():
    while True:
        try:
            api_id = int(input("Enter your API_ID here: "))
            if api_id > 0:
                break
        except ValueError:
            pass
        print(">> API_ID must be a positive integer.")
    while True:
        api_hash = input("Enter your API_HASH here: ").strip()
        if api_hash:
            return api_id, api_hash
        print(">> API_HASH must not be empty.")


async def generate(api_id, api_hash):
    import pyrogram as pyro

    library = "Pyrogram"
    print(generating.format(library, pyro.__version__))

    client = pyro.Client(
        "strgen",
        api_id=api_id,
        api_hash=api_hash,
        in_memory=True,
    )
    async with client:
        await asyncio.sleep(random.uniform(*DELAY_RANGE))
        string_session = await client.export_session_string()
        await asyncio.sleep(SHORT_DELAY)
        me = await client.get_me()
        text = saved_message.format(
            library=library,
            user_id=me.id,
            api_id=api_id,
            api_hash=api_hash,
            phone_number=me.phone_number,
            string_session=string_session,
        )
        print()
        print(string_session)
        await client.send_message(
            "me",
            text,
            parse_mode=pyro.enums.ParseMode.HTML,
        )


def main():
    try:
        ensure_package()
        print(usage)
        api_id, api_hash = get_api()
        asyncio.run(generate(api_id, api_hash))
        print(generated)
    except KeyboardInterrupt:
        print("\nCancelled.")
        sys.exit(130)
    except Exception as error:
        print(f">> {error}")
        sys.exit(1)


if __name__ == "__main__":
    main()
